import Head from 'next/head'
import Navbar from '../components/navbar'
import Intro from './intro'
import OurMission from './our_misson'
import OurVision from './our_vision'
import WhatWeDo from './what_we_do'
import OurProcess from './our_process'
import MeetTheTeam from './meet_the_team'
import ProjectPortfolio from './project_portfolio'
import AboutUs from './aboutus'
import Footer from './footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Harkani</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" absolute top-0 left-0 w-full h-fit flex flex-col items-center ">
        <Navbar/>
        <Intro/>
        <OurMission/>
        <OurVision/>
        <WhatWeDo/>
        <OurProcess/>
        <MeetTheTeam/>
        <ProjectPortfolio/>
        <AboutUs/>
        <Footer/>
          
      </main>
    </>
  )
}
